name: easacc_task
description: "task for easacc company."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #ui
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  loader_overlay: ^2.2.0
  flutter_screenutil: ^5.7.0
  dropdown_button2: ^2.3.9
  elegant_notification: ^1.11.2


  # State Management
  flutter_riverpod: any
  riverpod: ^2.2.0

  #local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  #utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  webview_flutter: ^4.2.2
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2

  #localization
  easy_localization: ^3.0.0

  # depend reference
  intl: ^0.18.0
  easy_logger: ^0.0.2

  # Debugging and Testing
  logging: ^1.1.1

  # Routing
  auto_route: ^7.8.4

  #firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6

  #social
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1



dev_dependencies:
  build_runner: ^2.3.2
  lint: ^2.0.1
  auto_route_generator: any

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
