// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hxfVD1xe1oJGD7ebqV8lbQhDesZ6bE0',
    appId: '1:383099215252:web:6bcf008beb16d8696c0381',
    messagingSenderId: '383099215252',
    projectId: 'eassac-d4385',
    authDomain: 'eassac-d4385.firebaseapp.com',
    storageBucket: 'eassac-d4385.appspot.com',
    measurementId: 'G-8D941QX5WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rGafyQkoH4uIGYq0WNBuLA-O6WihXVQ',
    appId: '1:383099215252:android:49fae45d0f56eaa76c0381',
    messagingSenderId: '383099215252',
    projectId: 'eassac-d4385',
    storageBucket: 'eassac-d4385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACtQaQE-v0pDR-BxAhEMhusSSjKwhl8IE',
    appId: '1:383099215252:ios:87e59a58cf8435b26c0381',
    messagingSenderId: '383099215252',
    projectId: 'eassac-d4385',
    storageBucket: 'eassac-d4385.appspot.com',
    iosClientId: '383099215252-brkkinm6l2ofjjsvro9j2b36pkdkjnba.apps.googleusercontent.com',
    iosBundleId: 'com.easacc.easaccTask',
  );
}
